create table question (
                          question_id bigint generated by default as identity,
                          content varchar(1000),
                          created_at timestamp,
                          member_id bigint not null,
                          title varchar(100) not null,
                          view_count bigint,
                          primary key (question_id)
);
create table reply (
                       reply_id bigint generated by default as identity,
                       content clob not null,
                       created_at timestamp,
                       member_id bigint not null,
                       question_id bigint not null,
                       primary key (reply_id)
);