create table comment (
                         comment_id bigint generated by default as identity,
                         content varchar(1000),
                         created_at timestamp not null,
                         member_id bigint not null,
                         reply_id bigint,
                         primary key (comment_id)
);
create table member (
                        member_id bigint generated by default as identity,
                        email varchar(255) not null,
                        name varchar(100) not null,
                        password varchar(100) not null,
                        primary key (member_id)
);
create table member_roles (
                              member_member_id bigint not null,
                              roles varchar(255)
);
create table question (
                          question_id bigint generated by default as identity,
                          content varchar(1000),
                          created_at timestamp,
                          member_id bigint not null,
                          title varchar(100) not null,
                          view_count bigint,
                          primary key (question_id)
);
create table reply (
                       reply_id bigint generated by default as identity,
                       choice bigint,
                       content clob not null,
                       created_at timestamp,
                       member_id bigint not null,
                       question_id bigint,
                       primary key (reply_id)
);